import { PacientesService } from './pacientes.service';
import { CreatePacienteDto } from './dto/create-paciente.dto';
import { UpdatePacienteDto } from './dto/update-paciente.dto';
import { SearchPacienteDto } from './dto/search-paciente.dto';
export declare class PacientesController {
    private readonly pacientesService;
    constructor(pacientesService: PacientesService);
    create(dto: CreatePacienteDto): import(".prisma/client").Prisma.Prisma__PacienteClient<{
        email: string | null;
        id: string;
        telefono: string;
        fotoUrl: string | null;
        createdAt: Date;
        updatedAt: Date;
        nombreCompleto: string;
        dni: string;
        fechaNacimiento: Date | null;
        telefonoAlternativo: string | null;
        direccion: string | null;
        obraSocialId: string | null;
        plan: string | null;
        alergias: string[];
        condiciones: string[];
        diagnostico: string | null;
        tratamiento: string | null;
        deriva: string | null;
        lugarIntervencion: string | null;
        objetivos: string | null;
        consentimientoFirmado: boolean;
        indicacionesEnviadas: boolean;
        fechaIndicaciones: Date | null;
        estado: import(".prisma/client").$Enums.EstadoPaciente;
        contactoEmergenciaNombre: string | null;
        contactoEmergenciaTelefono: string | null;
        contactoEmergenciaRelacion: string | null;
        usuarioId: string | null;
        profesionalId: string | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, import(".prisma/client").Prisma.PrismaClientOptions>;
    update(id: string, dto: UpdatePacienteDto): Promise<{
        email: string | null;
        id: string;
        telefono: string;
        fotoUrl: string | null;
        createdAt: Date;
        updatedAt: Date;
        nombreCompleto: string;
        dni: string;
        fechaNacimiento: Date | null;
        telefonoAlternativo: string | null;
        direccion: string | null;
        obraSocialId: string | null;
        plan: string | null;
        alergias: string[];
        condiciones: string[];
        diagnostico: string | null;
        tratamiento: string | null;
        deriva: string | null;
        lugarIntervencion: string | null;
        objetivos: string | null;
        consentimientoFirmado: boolean;
        indicacionesEnviadas: boolean;
        fechaIndicaciones: Date | null;
        estado: import(".prisma/client").$Enums.EstadoPaciente;
        contactoEmergenciaNombre: string | null;
        contactoEmergenciaTelefono: string | null;
        contactoEmergenciaRelacion: string | null;
        usuarioId: string | null;
        profesionalId: string | null;
    }>;
    delete(id: string): Promise<{
        email: string | null;
        id: string;
        telefono: string;
        fotoUrl: string | null;
        createdAt: Date;
        updatedAt: Date;
        nombreCompleto: string;
        dni: string;
        fechaNacimiento: Date | null;
        telefonoAlternativo: string | null;
        direccion: string | null;
        obraSocialId: string | null;
        plan: string | null;
        alergias: string[];
        condiciones: string[];
        diagnostico: string | null;
        tratamiento: string | null;
        deriva: string | null;
        lugarIntervencion: string | null;
        objetivos: string | null;
        consentimientoFirmado: boolean;
        indicacionesEnviadas: boolean;
        fechaIndicaciones: Date | null;
        estado: import(".prisma/client").$Enums.EstadoPaciente;
        contactoEmergenciaNombre: string | null;
        contactoEmergenciaTelefono: string | null;
        contactoEmergenciaRelacion: string | null;
        usuarioId: string | null;
        profesionalId: string | null;
    }>;
    suggest(res: any, q: string): Promise<import("../../common/types/paciente-suggest.type").PacienteSuggest[]>;
    search(query: SearchPacienteDto): Promise<{
        email: string | null;
        id: string;
        telefono: string;
        fotoUrl: string | null;
        createdAt: Date;
        updatedAt: Date;
        nombreCompleto: string;
        dni: string;
        fechaNacimiento: Date | null;
        telefonoAlternativo: string | null;
        direccion: string | null;
        obraSocialId: string | null;
        plan: string | null;
        alergias: string[];
        condiciones: string[];
        diagnostico: string | null;
        tratamiento: string | null;
        deriva: string | null;
        lugarIntervencion: string | null;
        objetivos: string | null;
        consentimientoFirmado: boolean;
        indicacionesEnviadas: boolean;
        fechaIndicaciones: Date | null;
        estado: import(".prisma/client").$Enums.EstadoPaciente;
        contactoEmergenciaNombre: string | null;
        contactoEmergenciaTelefono: string | null;
        contactoEmergenciaRelacion: string | null;
        usuarioId: string | null;
        profesionalId: string | null;
    }[] | {
        id: string;
        nombreCompleto: string;
        dni: string;
        telefono: string;
        score: number;
    }[]>;
    findOne(id: string): Promise<{
        email: string | null;
        id: string;
        telefono: string;
        fotoUrl: string | null;
        createdAt: Date;
        updatedAt: Date;
        nombreCompleto: string;
        dni: string;
        fechaNacimiento: Date | null;
        telefonoAlternativo: string | null;
        direccion: string | null;
        obraSocialId: string | null;
        plan: string | null;
        alergias: string[];
        condiciones: string[];
        diagnostico: string | null;
        tratamiento: string | null;
        deriva: string | null;
        lugarIntervencion: string | null;
        objetivos: string | null;
        consentimientoFirmado: boolean;
        indicacionesEnviadas: boolean;
        fechaIndicaciones: Date | null;
        estado: import(".prisma/client").$Enums.EstadoPaciente;
        contactoEmergenciaNombre: string | null;
        contactoEmergenciaTelefono: string | null;
        contactoEmergenciaRelacion: string | null;
        usuarioId: string | null;
        profesionalId: string | null;
    }>;
}
